import React from "react";

const ChampionshipsPage: React.FunctionComponent = () => {
    return (
        <div className="d-lg-flex align-items-start gap-4">
            <div className="flex-grow-1">
                <div className="card p-6 mb-4">
                    <div className="row">
                        <div className="col-12 text-center">
                            <h1>Кубок межсезонья</h1>
                        </div>
                    </div>
                    <div className="row">
                        <div className="col-12 text-center">
                            Сезон:
                            <select className="inline-block">
                                {Array.from({length: 10}).map((_, index: number) => (
                                    <option key={index}>{index + 1}</option>
                                ))}
                            </select>
                        </div>
                    </div>
                    <div className="row">
                        <div className="col-12 table-responsive">
                            <table className="table table-striped table-hover">
                                <thead>
                                <tr className="text-center">
                                    <th>М</th>
                                    <th>Команда</th>
                                    <th>И</th>
                                    <th>В</th>
                                    <th>Н</th>
                                    <th>П</th>
                                    <th>М+</th>
                                    <th>М-</th>
                                    <th>+/-</th>
                                    <th>О</th>
                                    <th>Vs</th>
                                    <th>РМ</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>Тростянец</td>
                                    <td>26</td>
                                    <td>20</td>
                                    <td>5</td>
                                    <td>1</td>
                                    <td>44</td>
                                    <td>4</td>
                                    <td>+40</td>
                                    <td>65</td>
                                    <td>3558</td>
                                    <td>680</td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>Шахтер</td>
                                    <td>26</td>
                                    <td>20</td>
                                    <td>1</td>
                                    <td>5</td>
                                    <td>73</td>
                                    <td>9</td>
                                    <td>+64</td>
                                    <td>61</td>
                                    <td>4246</td>
                                    <td>651</td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>Агрон{'\u00A0'}Великий{'\u00A0'}Гай</td>
                                    <td>26</td>
                                    <td>17</td>
                                    <td>3</td>
                                    <td>6</td>
                                    <td>53</td>
                                    <td>16</td>
                                    <td>+37</td>
                                    <td>54</td>
                                    <td>3935</td>
                                    <td>655</td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td>МФК{'\u00A0'}Николаев</td>
                                    <td>26</td>
                                    <td>15</td>
                                    <td>6</td>
                                    <td>5</td>
                                    <td>47</td>
                                    <td>24</td>
                                    <td>+23</td>
                                    <td>51</td>
                                    <td>3038</td>
                                    <td>616</td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td>Динамо{'\u00A0'}Киев</td>
                                    <td>26</td>
                                    <td>15</td>
                                    <td>5</td>
                                    <td>6</td>
                                    <td>46</td>
                                    <td>28</td>
                                    <td>+18</td>
                                    <td>50</td>
                                    <td>3400</td>
                                    <td>437</td>
                                </tr>
                                <tr>
                                    <td>6</td>
                                    <td>Подолье{'\u00A0'}Хмельницкий</td>
                                    <td>26</td>
                                    <td>14</td>
                                    <td>5</td>
                                    <td>7</td>
                                    <td>37</td>
                                    <td>21</td>
                                    <td>+16</td>
                                    <td>47</td>
                                    <td>2845</td>
                                    <td>660</td>
                                </tr>
                                <tr>
                                    <td>7</td>
                                    <td>Волынь{'\u00A0'}Луцк</td>
                                    <td>26</td>
                                    <td>13</td>
                                    <td>4</td>
                                    <td>9</td>
                                    <td>29</td>
                                    <td>39</td>
                                    <td>-10</td>
                                    <td>43</td>
                                    <td>2929</td>
                                    <td>697</td>
                                </tr>
                                <tr>
                                    <td>8</td>
                                    <td>Покуття{'\u00A0'}Коломыя</td>
                                    <td>26</td>
                                    <td>11</td>
                                    <td>3</td>
                                    <td>12</td>
                                    <td>22</td>
                                    <td>25</td>
                                    <td>-3</td>
                                    <td>36</td>
                                    <td>2794</td>
                                    <td>606</td>
                                </tr>
                                <tr>
                                    <td>9</td>
                                    <td>Металлист{'\u00A0'}Харьков</td>
                                    <td>26</td>
                                    <td>9</td>
                                    <td>7</td>
                                    <td>10</td>
                                    <td>31</td>
                                    <td>34</td>
                                    <td>-3</td>
                                    <td>34</td>
                                    <td>3021</td>
                                    <td>883</td>
                                </tr>
                                <tr>
                                    <td>10</td>
                                    <td>Ребель{'\u00A0'}Киев</td>
                                    <td>26</td>
                                    <td>8</td>
                                    <td>7</td>
                                    <td>11</td>
                                    <td>38</td>
                                    <td>41</td>
                                    <td>-3</td>
                                    <td>31</td>
                                    <td>2971</td>
                                    <td>568</td>
                                </tr>
                                <tr>
                                    <td>11</td>
                                    <td>Днепр-1</td>
                                    <td>26</td>
                                    <td>9</td>
                                    <td>1</td>
                                    <td>16</td>
                                    <td>25</td>
                                    <td>44</td>
                                    <td>-19</td>
                                    <td>28</td>
                                    <td>2726</td>
                                    <td>892</td>
                                </tr>
                                <tr>
                                    <td>12</td>
                                    <td>ВПК-Агро{'\u00A0'}Магдалиновка</td>
                                    <td>26</td>
                                    <td>7</td>
                                    <td>3</td>
                                    <td>16</td>
                                    <td>12</td>
                                    <td>47</td>
                                    <td>-35</td>
                                    <td>24</td>
                                    <td>2479</td>
                                    <td>595</td>
                                </tr>
                                <tr>
                                    <td>13</td>
                                    <td>Металлург</td>
                                    <td>26</td>
                                    <td>6</td>
                                    <td>4</td>
                                    <td>16</td>
                                    <td>29</td>
                                    <td>57</td>
                                    <td>-28</td>
                                    <td>22</td>
                                    <td>2982</td>
                                    <td>501</td>
                                </tr>
                                <tr>
                                    <td>14</td>
                                    <td>Диназ{'\u00A0'}Вышгород</td>
                                    <td>26</td>
                                    <td>6</td>
                                    <td>3</td>
                                    <td>17</td>
                                    <td>36</td>
                                    <td>53</td>
                                    <td>-17</td>
                                    <td>21</td>
                                    <td>2991</td>
                                    <td>359</td>
                                </tr>
                                <tr>
                                    <td>15</td>
                                    <td>Судостроитель{'\u00A0'}Николаев</td>
                                    <td>26</td>
                                    <td>5</td>
                                    <td>2</td>
                                    <td>19</td>
                                    <td>11</td>
                                    <td>49</td>
                                    <td>-38</td>
                                    <td>17</td>
                                    <td>2535</td>
                                    <td>521</td>
                                </tr>
                                <tr>
                                    <td>16</td>
                                    <td>Ворскла{'\u00A0'}Полтава</td>
                                    <td>26</td>
                                    <td>2</td>
                                    <td>3</td>
                                    <td>21</td>
                                    <td>14</td>
                                    <td>56</td>
                                    <td>-42</td>
                                    <td>9</td>
                                    <td>2776</td>
                                    <td>520</td>
                                </tr>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>М</th>
                                    <th>Команда</th>
                                    <th>И</th>
                                    <th>В</th>
                                    <th>Н</th>
                                    <th>П</th>
                                    <th>М+</th>
                                    <th>М-</th>
                                    <th>+/-</th>
                                    <th>О</th>
                                    <th>Vs</th>
                                    <th>РМ</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default ChampionshipsPage;
