import type { Metadata } from "next";
import { Figtree } from 'next/font/google'
import "../scss/style.scss";
import React from "react";

const figtree = Figtree({
    subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-bs-theme="light" className={figtree.className}>
      <body className="hstack p-5 h-screen">
        {children}
      </body>
    </html>
  );
}
