import type {Metadata} from "next";
import {Figtree} from 'next/font/google'
import "../styles/style.scss";
import React from "react";
import NavBar from "@/partials/_nav-bar";
import Sidebar from "@/partials/_sidebar";
import SidebarToggle from "@/partials/_sidebar-toggle";

const figtree = Figtree({
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="en" data-bs-theme="light" className={figtree.className}>
        <body className="hstack p-5 h-screen">
        <Sidebar/>
        <div id="content" data-simplebar>
            <div className="content-body content-body-centered">
                <div className="header">
                    <SidebarToggle/>
                    <h2 className="header-title ps-xl-2">Home</h2>

                    <nav aria-label="breadcrumb" className="ms-6 d-none d-sm-flex">
                        <ol className="breadcrumb">
                            <li className="breadcrumb-item active" aria-current="page">
                                Home
                            </li>
                        </ol>
                    </nav>

                    <div className="d-flex gap-2 ms-auto">
                        <a href="" className="icon ph ph-arrow-clockwise"></a>
                        <a href="" className="icon ph ph-gear"></a>
                    </div>
                </div>
                {children}
            </div>
        </div>
        <NavBar/>
        </body>
        </html>
    );
}
