<?php
declare(strict_types=1);

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    private const array CITIES = [
        'England' => [
            'Birmingham',
            'Bournemouth',
            'Brentford',
            'Brighton and Hove',
            'Leeds',
            'Liverpool',
            'London',
            'Manchester',
            'Newcastle upon Tyne',
            'Stoke-on-Trent',
            'Sunderland',
        ],
        'France' => [
            'Angers',
            'Auxerre',
            'Brest',
            'Le Havre',
            'Lens',
            'Lille',
            'Lorient',
            'Lyon',
            'Marseille',
            'Metz',
            'Nantes',
            'Nice',
            'Paris',
            'Rennes',
            'Strasbourg',
            'Toulouse',
        ],
        'Spain' => [
            'Barcelona',
            'Bilbao',
            'Getafe',
            'Girona',
            'Madrid',
            'Majorca',
            'Pamplona',
            'San Sebastian',
            'Seville',
            'Valencia',
            'Vigo',
            'Villarreal',
            'Vitoria-Gasteiz',
        ],
        'Italy' => [
            'Bergamo',
            'Bologna',
            'Cagliari',
            'Como',
            'Florence',
            'Genoa',
            'Milan',
            'Naples',
            'Parma',
            'Rome',
            'Sassuolo',
            'Turin',
            'Udine',
        ],
        'Germany' => [
            'Augsburg',
            'Berlin',
            'Bremen',
            'Cologne',
            'Dortmund',
            'Frankfurt am Main',
            'Freiburg im Breisgau',
            'Hamburg',
            'Hoffenheim',
            'Leipzig',
            'Leverkusen',
            'Mainz',
            'Monchengladbach',
            'Munich',
            'Stuttgart',
            'Wolfsburg',
        ],
        'Argentina' => [
            'Avellaneda',
            'Buenos Aires',
            'Cordoba',
            'Florencio Varela',
            'La Plata',
            'Lanus',
            'Rivadavia',
            'Rosario',
            'Santa Fe',
            'Victoria',
        ],
        'Brazil' => [
            'Belo Horizonte',
            'Braganca Paulista',
            'Curitiba',
            'Porto Alegre',
            'Ribeirao Preto',
            'Rio de Janeiro',
            'Salvador',
            'Santos',
            'Sao Paulo',
        ],
        'Mexico' => [
            'Aguascalientes',
            'Ciudad Juarez',
            'Guadalajara',
            'Leon',
            'Mexico City',
            'Monterrey',
            'Pachuca',
            'Puebla',
            'San Luis Potosi',
            'Santiago de Queretaro',
            'Tijuana',
            'Toluca',
        ],
        'Portugal' => [
            'Alverca do Ribatejo',
            'Amadora',
            'Arouca',
            'Barcelos',
            'Braga',
            'Estoril',
            'Funchal',
            'Guimaraes',
            'Lisbon',
            'Moreira de Conegos',
            'Ponta Delgada',
            'Porto',
            'Vila do Conde',
            'Vila Nova de Famalicao',
        ],
        'Colombia' => [
            'Barranquilla',
            'Bogota',
            'Bucaramanga',
            'Cali',
            'Cucuta',
            'Manizales',
            'Medellín',
            'Pasto',
            'Rionegro',
            'Tolima',
            'Villavicencio',
        ],
        'Netherlands' => [
            'Alkmaar',
            'Amsterdam',
            'Deventer',
            'Eindhoven',
            'Enschede',
            'Groningen',
            'Heerenveen',
            'Nijmegen',
            'Rotterdam',
            'Sittard',
            'Utrecht',
            'Velsen-Zuid',
            'Volendam',
            'Zwolle',
        ],
        'Uruguay' => [
            'Las Piedras',
            'Maldonado',
            'Melo',
            'Montevideo',
        ],
        'Belgium' => [
            'Anderlecht',
            'Antwerp',
            'Bruges',
            'Brussels',
            'Charleroi',
            'Denderleeuw',
            'Genk',
            'Ghent',
            'La Louviere',
            'Leuven',
            'Liege',
            'Mechelen',
            'Sint-Truiden',
            'Waregem',
            'Westerlo',
        ],
        'Turkey' => [
            'Alanya',
            'Ankara',
            'Antalya',
            'Basaksehir',
            'Besiktas',
            'Gaziantep',
            'Istanbul',
            'Izmir',
            'Kadikoy',
            'Kasimpasa',
            'Kayseri',
            'Kocaeli',
            'Konya',
            'Rize',
            'Samsun',
            'Trabzon',
        ],
        'Ecuador' => [
            'Ambato',
            'Atuntaqui',
            'Cuenca',
            'Guayaquil',
            'Loja',
            'Machala',
            'Manta',
            'Quito',
        ],
        'Paraguay' => [
            'Asuncion',
            'Capiata',
            'Doctor Juan Leon Mallorquin',
            'Luque',
            'Pedro Juan Caballero',
            'Pinoza',
            'San Lorenzo',
            'Villa Elisa',
            'Villa Hayes',
        ],
    ];

    public function run(): void
    {
        City::query()->truncate();

        foreach (self::CITIES as $countryName => $cities) {
            $country = Country::query()->where('name', $countryName)->first();
            foreach ($cities as $city) {
                $model = new City();
                $model->name = $city;
                $model->country()->associate($country);
                $model->save();
            }
        }
    }
}
