<?php
declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    private const array COUNTRIES = [
        ['name' => 'Afghanistan', 'code' => 'AFG'],
        ['name' => 'Albania', 'code' => 'ALB'],
        ['name' => 'Algeria', 'code' => 'DZA'],
        ['name' => 'American Samoa', 'code' => 'ASM'],
        ['name' => 'Andorra', 'code' => 'AND'],
        ['name' => 'Angola', 'code' => 'AGO'],
        ['name' => 'Anguilla', 'code' => 'AIA'],
        ['name' => 'Antarctic', 'code' => 'ATA'],
        ['name' => 'Antigua and Barbuda', 'code' => 'ATG'],
        ['name' => 'Argentina', 'code' => 'ARG'],
        ['name' => 'Armenia', 'code' => 'ARM'],
        ['name' => 'Aruba', 'code' => 'ABW'],
        ['name' => 'Australia', 'code' => 'AUS'],
        ['name' => 'Austria', 'code' => 'AUT'],
        ['name' => 'Azerbaijan', 'code' => 'AZE'],
        ['name' => 'Bahamas', 'code' => 'BHS'],
        ['name' => 'Bahrain', 'code' => 'BHR'],
        ['name' => 'Bangladesh', 'code' => 'BGD'],
        ['name' => 'Barbados', 'code' => 'BRB'],
        ['name' => 'Belarus', 'code' => 'BLR'],
        ['name' => 'Belgium', 'code' => 'BEL'],
        ['name' => 'Belize', 'code' => 'BLZ'],
        ['name' => 'Benin', 'code' => 'BEN'],
        ['name' => 'Bermuda', 'code' => 'BMU'],
        ['name' => 'Bhutan', 'code' => 'BTN'],
        ['name' => 'Bolivia', 'code' => 'BOL'],
        ['name' => 'Bosnia & Herzegovina', 'code' => 'BIH'],
        ['name' => 'Botswana', 'code' => 'BWA'],
        ['name' => 'Bouvet Island', 'code' => 'BVT'],
        ['name' => 'Brazil', 'code' => 'BRA'],
        ['name' => 'British Indian Ocean Territory', 'code' => 'IOT'],
        ['name' => 'Brunei Darussalam', 'code' => 'BRN'],
        ['name' => 'Bulgaria', 'code' => 'BGR'],
        ['name' => 'Burkina-Faso', 'code' => 'BFA'],
        ['name' => 'Burundi', 'code' => 'BDI'],
        ['name' => 'Cambodia', 'code' => 'KHM'],
        ['name' => 'Cameroon', 'code' => 'CMR'],
        ['name' => 'Canada', 'code' => 'CAN'],
        ['name' => 'Cape Verde', 'code' => 'CPV'],
        ['name' => 'Cayman Islands', 'code' => 'CYM'],
        ['name' => 'Central African Republic', 'code' => 'CAF'],
        ['name' => 'Chad', 'code' => 'TCD'],
        ['name' => 'Chili', 'code' => 'CHL'],
        ['name' => 'China', 'code' => 'CHN'],
        ['name' => 'Christmas Island', 'code' => 'CXR'],
        ['name' => 'Cocos (Keeling) Islands', 'code' => 'CCK'],
        ['name' => 'Colombia', 'code' => 'COL'],
        ['name' => 'Comoros', 'code' => 'COM'],
        ['name' => 'Congo', 'code' => 'COG'],
        ['name' => 'Congo, Democratic Republic of the', 'code' => 'COD'],
        ['name' => 'Cook Islands', 'code' => 'COK'],
        ['name' => 'Costa Rica', 'code' => 'CRI'],
        ['name' => 'Cote d\'Ivoire', 'code' => 'CIV'],
        ['name' => 'Croatia', 'code' => 'HRV'],
        ['name' => 'Cuba', 'code' => 'CUB'],
        ['name' => 'Cyprus', 'code' => 'CYP'],
        ['name' => 'Czech Republic', 'code' => 'CZE'],
        ['name' => 'Denmark', 'code' => 'DNK'],
        ['name' => 'Djibouti', 'code' => 'DJI'],
        ['name' => 'Dominica', 'code' => 'DMA'],
        ['name' => 'Dominican Republic', 'code' => 'DOM'],
        ['name' => 'East Timor', 'code' => 'TMP'],
        ['name' => 'Ecuador', 'code' => 'ECU'],
        ['name' => 'Egypt', 'code' => 'EGY'],
        ['name' => 'El Salvador', 'code' => 'SLV'],
        ['name' => 'England', 'code' => 'ENG'],
        ['name' => 'Equatorial Guinea', 'code' => 'GNQ'],
        ['name' => 'Eritrea', 'code' => 'ERI'],
        ['name' => 'Estonia', 'code' => 'EST'],
        ['name' => 'Ethiopia', 'code' => 'ETH'],
        ['name' => 'Falkland (Malvinas) Islands', 'code' => 'FLK'],
        ['name' => 'Faroe Islands', 'code' => 'FRO'],
        ['name' => 'Federated States of Micronesia', 'code' => 'FSM'],
        ['name' => 'Fiji', 'code' => 'FJI'],
        ['name' => 'Finland', 'code' => 'FIN'],
        ['name' => 'France', 'code' => 'FRA'],
        ['name' => 'French Guyana', 'code' => 'GUF'],
        ['name' => 'French Polynesia', 'code' => 'PYF'],
        ['name' => 'French Southern Territories', 'code' => 'ATF'],
        ['name' => 'Gabon', 'code' => 'GAB'],
        ['name' => 'Gambia', 'code' => 'GMB'],
        ['name' => 'Georgia', 'code' => 'GEO'],
        ['name' => 'Germany', 'code' => 'DEU'],
        ['name' => 'Ghana', 'code' => 'GHA'],
        ['name' => 'Gibraltar', 'code' => 'GIB'],
        ['name' => 'Great Britain (United Kingdom)', 'code' => 'GBR'],
        ['name' => 'Greece', 'code' => 'GRC'],
        ['name' => 'Greenland', 'code' => 'GRL'],
        ['name' => 'Grenada', 'code' => 'GRD'],
        ['name' => 'Guadeloupe', 'code' => 'GLP'],
        ['name' => 'Guam', 'code' => 'GUM'],
        ['name' => 'Guatemala', 'code' => 'GTM'],
        ['name' => 'Guinea', 'code' => 'GIN'],
        ['name' => 'Guinea-Bissau', 'code' => 'GNB'],
        ['name' => 'Guyana', 'code' => 'GUY'],
        ['name' => 'Haiti', 'code' => 'HTI'],
        ['name' => 'Heard and McDonald Islands', 'code' => 'HMD'],
        ['name' => 'Honduras', 'code' => 'HND'],
        ['name' => 'Hong Kong', 'code' => 'HKG'],
        ['name' => 'Hungary', 'code' => 'HUN'],
        ['name' => 'Iceland', 'code' => 'ISL'],
        ['name' => 'India', 'code' => 'IND'],
        ['name' => 'Indonesia', 'code' => 'IDN'],
        ['name' => 'Iran', 'code' => 'IRN'],
        ['name' => 'Iraq', 'code' => 'IRQ'],
        ['name' => 'Ireland', 'code' => 'IRL'],
        ['name' => 'Israel', 'code' => 'ISR'],
        ['name' => 'Italy', 'code' => 'ITA'],
        ['name' => 'Jamaica', 'code' => 'JAM'],
        ['name' => 'Japan', 'code' => 'JPN'],
        ['name' => 'Jordan', 'code' => 'JOR'],
        ['name' => 'Kazakhstan', 'code' => 'KAZ'],
        ['name' => 'Kenya', 'code' => 'KEN'],
        ['name' => 'Kirghizstan', 'code' => 'KGZ'],
        ['name' => 'Kiribati', 'code' => 'KIR'],
        ['name' => 'Korea (North)', 'code' => 'PRK'],
        ['name' => 'Korea (South)', 'code' => 'KOR'],
        ['name' => 'Kuwait', 'code' => 'KWT'],
        ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LAO'],
        ['name' => 'Latvia', 'code' => 'LVA'],
        ['name' => 'Lebanon', 'code' => 'LBN'],
        ['name' => 'Lesotho', 'code' => 'LSO'],
        ['name' => 'Liberia', 'code' => 'LBR'],
        ['name' => 'Libyan Arab Jamahiriya', 'code' => 'LBY'],
        ['name' => 'Liechtenstein', 'code' => 'LIE'],
        ['name' => 'Lithuania', 'code' => 'LTU'],
        ['name' => 'Luxembourg', 'code' => 'LUX'],
        ['name' => 'Macau (Macao)', 'code' => 'MAC'],
        ['name' => 'Macedonia', 'code' => 'MKD'],
        ['name' => 'Madagascar', 'code' => 'MDG'],
        ['name' => 'Malawi', 'code' => 'MWI'],
        ['name' => 'Malaysia', 'code' => 'MYS'],
        ['name' => 'Maldives', 'code' => 'MDV'],
        ['name' => 'Mali', 'code' => 'MLI'],
        ['name' => 'Malta', 'code' => 'MLT'],
        ['name' => 'Marocco', 'code' => 'MAR'],
        ['name' => 'Marshall Islands', 'code' => 'MHL'],
        ['name' => 'Martinique', 'code' => 'MTQ'],
        ['name' => 'Mauritania', 'code' => 'MRT'],
        ['name' => 'Mauritius', 'code' => 'MUS'],
        ['name' => 'Mayotte', 'code' => 'MYT'],
        ['name' => 'Mexico', 'code' => 'MEX'],
        ['name' => 'Moldova', 'code' => 'MDA'],
        ['name' => 'Monaco', 'code' => 'MCO'],
        ['name' => 'Mongolia', 'code' => 'MNG'],
        ['name' => 'Montserrat', 'code' => 'MSR'],
        ['name' => 'Mozambique', 'code' => 'MOZ'],
        ['name' => 'Myanmar', 'code' => 'MMR'],
        ['name' => 'Namibia', 'code' => 'NAM'],
        ['name' => 'Nauru', 'code' => 'NRU'],
        ['name' => 'Nepal', 'code' => 'NPL'],
        ['name' => 'Netherlands (Holland)', 'code' => 'NLD'],
        ['name' => 'Netherlands\' Antilles', 'code' => 'ANT'],
        ['name' => 'new Caledonia', 'code' => 'NCL'],
        ['name' => 'new Zealand', 'code' => 'NZL'],
        ['name' => 'Nicaragua', 'code' => 'NIC'],
        ['name' => 'Niger', 'code' => 'NER'],
        ['name' => 'Nigeria', 'code' => 'NGA'],
        ['name' => 'Niue', 'code' => 'NIU'],
        ['name' => 'Norfolk Island', 'code' => 'NFK'],
        ['name' => 'Northern Ireland', 'code' => 'NIR'],
        ['name' => 'Northern Mariana Islands', 'code' => 'MNP'],
        ['name' => 'Norway', 'code' => 'NOR'],
        ['name' => 'Oman', 'code' => 'OMN'],
        ['name' => 'Pakistan', 'code' => 'PAK'],
        ['name' => 'Palau', 'code' => 'PLW'],
        ['name' => 'Palestinian Territory (occupied)', 'code' => '?'],
        ['name' => 'Panama', 'code' => 'PAN'],
        ['name' => 'Papua new Guinea', 'code' => 'PNG'],
        ['name' => 'Paraguay', 'code' => 'PRY'],
        ['name' => 'Peru', 'code' => 'PER'],
        ['name' => 'Philippines', 'code' => 'PHL'],
        ['name' => 'Pitcairn', 'code' => 'PCN'],
        ['name' => 'Poland', 'code' => 'POL'],
        ['name' => 'Portugal', 'code' => 'PRT'],
        ['name' => 'Puerto Rico', 'code' => 'PRI'],
        ['name' => 'Qatar', 'code' => 'QAT'],
        ['name' => 'Reunion', 'code' => 'REU'],
        ['name' => 'Romania', 'code' => 'ROM'],
        ['name' => 'Russia (Russian Federation)', 'code' => 'RUS'],
        ['name' => 'Rwanda', 'code' => 'RWA'],
        ['name' => 'Saint Kitts (Christopher) and Nevis', 'code' => 'KNA'],
        ['name' => 'Saint Lucia', 'code' => 'LCA'],
        ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VCT'],
        ['name' => 'Samoa', 'code' => 'WSM'],
        ['name' => 'San Marino', 'code' => 'SMR'],
        ['name' => 'Sao Tomea and Principe', 'code' => 'STP'],
        ['name' => 'Saudi Arabia', 'code' => 'SAU'],
        ['name' => 'Scotland', 'code' => 'SCT'],
        ['name' => 'Senegal', 'code' => 'SEN'],
        ['name' => 'Seychelles', 'code' => 'SYC'],
        ['name' => 'Sierra Leone', 'code' => 'SLE'],
        ['name' => 'Singapore', 'code' => 'SGP'],
        ['name' => 'Slovak Republic', 'code' => 'SVK'],
        ['name' => 'Slovenia', 'code' => 'SVN'],
        ['name' => 'Solomon Islands', 'code' => 'SLB'],
        ['name' => 'Somali', 'code' => 'SOM'],
        ['name' => 'South Africa', 'code' => 'ZAF'],
        ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'SGS'],
        ['name' => 'Spain', 'code' => 'ESP'],
        ['name' => 'Sri Lanka', 'code' => 'LKA'],
        ['name' => 'St. Helena', 'code' => 'SHN'],
        ['name' => 'St. Pierre and Miquelon', 'code' => 'SPM'],
        ['name' => 'Sudan', 'code' => 'SDN'],
        ['name' => 'Surinam', 'code' => 'SUR'],
        ['name' => 'Svalbard and Jan Mayen Islands', 'code' => 'SJM'],
        ['name' => 'Swaziland', 'code' => 'SWZ'],
        ['name' => 'Sweden', 'code' => 'SWE'],
        ['name' => 'Switzerland', 'code' => 'CHE'],
        ['name' => 'Syria', 'code' => 'SYR'],
        ['name' => 'Tadjikistan', 'code' => 'TJK'],
        ['name' => 'Taiwan', 'code' => 'TWN'],
        ['name' => 'Tanzania', 'code' => 'TZA'],
        ['name' => 'Thailand', 'code' => 'THA'],
        ['name' => 'Togo', 'code' => 'TGO'],
        ['name' => 'Tokelau', 'code' => 'TKL'],
        ['name' => 'Tonga', 'code' => 'TON'],
        ['name' => 'Trinidad and Tobago', 'code' => 'TTO'],
        ['name' => 'Tunisia', 'code' => 'TUN'],
        ['name' => 'Turkey', 'code' => 'TUR'],
        ['name' => 'Turkmenistan', 'code' => 'TKM'],
        ['name' => 'Turks and Caicos Islands', 'code' => 'TCA'],
        ['name' => 'Tuvalu', 'code' => 'TUV'],
        ['name' => 'Uganda', 'code' => 'UGA'],
        ['name' => 'Ukraine', 'code' => 'UKR'],
        ['name' => 'United Arab Emirates', 'code' => 'ARE'],
        ['name' => 'United States Minor Outlying Islands', 'code' => 'UMI'],
        ['name' => 'United States of America', 'code' => 'USA'],
        ['name' => 'Uruguay', 'code' => 'URY'],
        ['name' => 'Uzbekistan', 'code' => 'UZB'],
        ['name' => 'Vanuatu', 'code' => 'VUT'],
        ['name' => 'Vatican (Holy See)', 'code' => 'VAT'],
        ['name' => 'Venezuela', 'code' => 'VEN'],
        ['name' => 'Viet Nam', 'code' => 'VNM'],
        ['name' => 'Virgin Islands, British', 'code' => 'VGB'],
        ['name' => 'Virgin Islands, US', 'code' => 'VIR'],
        ['name' => 'Wales', 'code' => 'WLS'],
        ['name' => 'Wallis and Futuna Islands', 'code' => 'WLF'],
        ['name' => 'Western Sahara', 'code' => 'ESH'],
        ['name' => 'Yemen', 'code' => 'YEM'],
        ['name' => 'Yugoslavia', 'code' => 'YUG'],
        ['name' => 'Zambia', 'code' => 'ZMB'],
        ['name' => 'Zimbabwe', 'code' => 'ZWE'],
    ];

    public function run(): void
    {
        Country::query()->truncate();

        foreach (self::COUNTRIES as $country) {
            $model = new Country();
            $model->name = $country['name'];
            $model->code = $country['code'];
            $model->save();
        }
    }
}
