name: laravel phpmd
run-name: laravel phpmd

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: read

jobs:
    laravel-phpmd:
        name: phpmd
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@aa1fe473f9c687b6fb896056d771232c0bc41161
                with:
                    php-version: '8.3'
                    coverage: none
                    tools: phpmd

            -   name: Install composer dependencies
                run: |
                    cd laravel
                    composer install -n --prefer-dist

            -   name: Run PHPMD
                run: |
                    cd laravel
                    phpmd . github phpmd.xml
